### ISSUE TITLE
RBP_alignmentscores.txt is missing

### ISSUE THREAD

**Issue by ptynecki** [dimiboeckaerts/BacteriophageHostPrediction#1]
Good morning,

Could you share `RBP_alignmentscores.txt` file required to final preprocessing in `RBP_host_prediction.ipynb`?

Regards,
Piotr

**Comment by dimiboeckaerts** [comment]
Hi Piotr, thanks for your message! I haven't uploaded the `RBP_alignmentscores.txt` file as you can compute the alignment scores yourself with the `RBP_alignment.jl` file (which computes the alignments in Julia, though you can easily do it in Python as well if you prefer). But if you want, I can send you the file via email if you give me your address.

If you have any other questions or comments, don't hesitate to contact me (you can always send me an email at Dimitri.Boeckaerts@UGent.be).

Kind regards, Dimi
